# Generated by Django 5.2.3 on 2025-06-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='products',
            field=models.ManyToManyField(related_name='reviews', to='examples.product'),
        ),
    ]
